name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

env:
  SITE_TITLE: U Pull RSS (U Pull R Parts Inventory Feed)
  SITE_URL: https://pinjasaur.github.io/u-pull-rss
  FEED_SIZE_PLUS_ONE: 11

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Grab LTS Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Fetch latest inventory as HTML
      run: |-
        curl 'https://upullrparts.com/wp-admin/admin-ajax.php' --compressed -X POST --data-raw 'action=getVehicles' | sed 's/<br>//g' > inventory.html
    - name: Convert HTML to Markdown
      run: |-
        npx -y @wcj/html-to-markdown-cli inventory.html -o .
        mv -f inventory.html.md inventory.md
        rm -f inventory.html
    - name: Commit and push if it changed
      run: |-
        [[ -z "$(git status --porcelain)" ]] && exit 0
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        yyyymmdd=$(date +%F)
        mkdir -p changelog

        diff="$(git diff | awk '{ seen[substr($0,2)]++; l[i++] = $0; } END { for (j = 0; j < i; ++j) if (seen[substr(l[j],2)] < 2) print l[j] }' | grep '^[+-][^+-]' | sort)"
        if [[ -n "$diff" ]]; then
          echo "> Last updated: ${yyyymmdd}" > changelog/"${yyyymmdd}".md
          echo "Stock numbers are prefixed with \`UG\` for Rosemount and \`NG\` for East Bethel." >> changelog/"${yyyymmdd}".md
          echo '```diff' >> changelog/"${yyyymmdd}".md
          echo "$diff" >> changelog/"${yyyymmdd}".md
          echo '```' >> changelog/"${yyyymmdd}".md
          echo "- [${yyyymmdd}](./${yyyymmdd})" >> changelog/index.md
        fi

        cat <<EOF> feed.rss
        <?xml version="1.0" encoding="UTF-8"?>
        <rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
          <channel>
            <title><![CDATA[ $SITE_TITLE ]]></title>
            <link>$SITE_URL</link>
            <atom:link href="$SITE_URL/feed.rss" rel="self" type="application/rss+xml"/>
            <description><![CDATA[ The feed of updates to $SITE_TITLE ]]></description>
        EOF

        for file in $(ls -rU changelog | head -$FEED_SIZE_PLUS_ONE); do
          date="$(basename "${file}" .md)"
          [[ "$date" == "index" ]] && continue
          html="$(pandoc -t html5 changelog/"$file" | sed -e 's/<span class="va">/<span style="color:green" class="va">/g' -e 's/<span class="st">/<span style="color:red" class="st">/g')"
          cat <<EOF>> feed.rss
            <item>
              <title><![CDATA[ $date ]]></title>
              <link>$SITE_URL/changelog/$date</link>
              <guid isPermaLink="false">$date</guid>
              <pubDate>$date</pubDate>
              <description><![CDATA[ $html ]]></description>
            </item>
        EOF
        done

        cat <<EOF>> feed.rss
          </channel>
        </rss>
        EOF

        git add -A
        git commit -m "Latest data: ${yyyymmdd}"
        git push
