name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

env:
  DIFFTASTIC_VERSION: 0.50.0

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -y aha
    - name: Difftastic
      run: |
        curl -sL https://github.com/Wilfred/difftastic/releases/download/$DIFFTASTIC_VERSION/difft-x86_64-unknown-linux-gnu.tar.gz -o difftastic-$DIFFTASTIC_VERSION.tar.gz && \
        tar -xzvf difftastic-$DIFFTASTIC_VERSION.tar.gz && \
        mv difft /usr/local/bin && \
        rm -f difftastic-$DIFFTASTIC_VERSION.tar.gz
    - name: Fetch latest data
      run: |-
        curl 'https://upullrparts.com/wp-admin/admin-ajax.php' --compressed -X POST --data-raw 'action=getVehicles' > inventory.html
    - name: Commit and push if it changed
      run: |-
        [[ -z "$(git status --porcelain)" ]] && exit 0
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        yyyymmdd=$(date +%F)
        mkdir -p changelog
        GIT_EXTERNAL_DIFF=difft git diff --color | tail -n +5 | aha -t "${yyyymmdd}" > changelog/"${yyyymmdd}".html
        git add -A
        git commit -m "Latest data: ${yyyymmdd}"
        git push
