name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Grab LTS Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Fetch latest inventory as HTML
      run: |-
        curl 'https://upullrparts.com/wp-admin/admin-ajax.php' --compressed -X POST --data-raw 'action=getVehicles' | sed 's/<br>//g' > inventory.html
    - name: Convert HTML to Markdown
      run: |-
        npx -y @wcj/html-to-markdown-cli inventory.html -o .
        mv -f inventory.html.md inventory.md
        rm -f inventory.html
    - name: Commit and push if it changed
      run: |-
        [[ -z "$(git status --porcelain)" ]] && exit 0
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        yyyymmdd=$(date +%F)
        mkdir -p changelog
        
        echo '```diff' > changelog/"${yyyymmdd}".md
        git diff | awk '{ seen[substr($0,2)]++; l[i++] = $0; } END { for (j = 0; j < i; ++j) if (seen[substr(l[j],2)] < 2) print l[j] }' | grep '^[+-][^+-]' | sort >> changelog/"${yyyymmdd}".md
        echo '```' >> changelog/"${yyyymmdd}".md
        pandoc -t html5 diff.md | sed -e 's/<span class="va">/<span style="color:green" class="va">/g' -e 's/<span class="st">/<span style="color:red" class="st">/g' > changelog/"${yyyymmdd}".html
        
        git add -A
        git commit -m "Latest data: ${yyyymmdd}"
        git push
