name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Grab LTS Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -y aha
    - name: Fetch latest inventory as HTML
      run: |-
        curl 'https://upullrparts.com/wp-admin/admin-ajax.php' --compressed -X POST --data-raw 'action=getVehicles' | sed 's/<br>//g' > inventory.html
    - name: Convert HTML to Markdown
      run: |-
        npx -y @wcj/html-to-markdown-cli inventory.html -o .
        mv -f inventory.html.md inventory.md
        rm -f inventory.html
    - name: Commit and push if it changed
      run: |-
        [[ -z "$(git status --porcelain)" ]] && exit 0
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        yyyymmdd=$(date +%F)
        mkdir -p changelog
        git diff --color | tail -n +5 | aha -t "${yyyymmdd}" > changelog/"${yyyymmdd}".html
        git add -A
        git commit -m "Latest data: ${yyyymmdd}"
        git push
